name: Frontend React App Deploy

on:
  push:
    paths:
      - "app/frontend/**"
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install and Build React App
        run: |
          cd app/frontend/react-app
          npm install
          npm run build

      - name: Sync Build to S3
        run: |
          aws s3 sync app/frontend/react-app/build s3://${{ secrets.S3_BUCKET_NAME }} --delete
