name: Build and Push Backend Microservices

on:
  push:
    branches:
      - main
    paths:
      - 'app/backend/**'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Order Service
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URL }}:order-service ./app/backend/order-service
          docker push ${{ secrets.ECR_REPOSITORY_URL }}:order-service

      - name: Build and Push Product Service
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URL }}:product-service ./app/backend/product-service
          docker push ${{ secrets.ECR_REPOSITORY_URL }}:product-service

      - name: Build and Push User Service
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URL }}:user-service ./app/backend/user-service
          docker push ${{ secrets.ECR_REPOSITORY_URL }}:user-service

